//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XpoDataModelExample.Module.BusinessObjects.NewDataModel
{

    public partial class Employee : XPObject
    {
        string fFirstName;
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fLastName;
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>(nameof(LastName), ref fLastName, value); }
        }
        DateTime fBirthday;
        public DateTime Birthday
        {
            get { return fBirthday; }
            set { SetPropertyValue<DateTime>(nameof(Birthday), ref fBirthday, value); }
        }
        [PersistentAlias("[FirstName] + '' + [LastName]")]
        public string FullName
        {
            get { return (string)(EvaluateAlias(nameof(FullName))); }
        }
        [Association(@"TaskReferencesEmployee")]
        public XPCollection<Task> Tasks { get { return GetCollection<Task>(nameof(Tasks)); } }
    }

}
