//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace XpoDataModelExample.Module.BusinessObjects.NewDataModel
{

    public partial class Task : XPObject
    {
        string fSubject;
        public string Subject
        {
            get { return fSubject; }
            set { SetPropertyValue<string>(nameof(Subject), ref fSubject, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        Employee fAssignedTo;
        [Association(@"TaskReferencesEmployee")]
        public Employee AssignedTo
        {
            get { return fAssignedTo; }
            set { SetPropertyValue<Employee>(nameof(AssignedTo), ref fAssignedTo, value); }
        }
    }

}
